// All shared types now live in @gelehka/shared.
// This module re-exports them so existing server imports continue to work.
export type {
  AoeIndicator,
  BossPhase,
  BossKind,
  BossSnapshot,
  BossState,
  ClientChatMessage,
  ClientMessage,
  Direction,
  DropSnapshot,
  EnemyKind,
  EnemySnapshot,
  EnemyStateDelta,
  EnemyTransformSnapshot,
  HazardKind,
  HazardSnapshot,
  IceZone,
  InstanceId,
  InputMessage,
  JoinMessage,
  LeaderboardMessage,
  PlayerLeaderboardEntry,
  PlayerSnapshot,
  PacmanGhostVariant,
  PlayerState,
  ProtocolVersion,
  ServerChatMessage,
  ServerMessage,
  BlobSnapshot,
  BlobState,
  EnemyState,
  SnapshotDeltaMessage,
  SnapshotMessage,
  PortalKind,
  PortalSnapshot,
  WelcomeMessage,
} from '@gelehka/shared';

export {
  BOSS_KINDS,
  CLIENT_MESSAGE_TYPES,
  DROP_KINDS,
  ENEMY_KINDS,
  HAZARD_KINDS,
  INSTANCE_IDS,
  PACMAN_GHOST_VARIANTS,
  PLAYER_STATUS_EFFECTS,
  PORTAL_KINDS,
  SERVER_MESSAGE_TYPES,
} from '@gelehka/shared';
